console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[upgrade]
source = 'cdn'
interval = '168h'
auto = false
notice = false

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = "os"
style = "plain"
foreground = "p:red"
template = '{{ .Icon }}  '

[[blocks.segments]]
type = "session"
style = "plain"
foreground = "p:yellow"
template = '{{ .UserName }}'

[[blocks.segments]]
type = 'text'
style = 'plain'
foreground = 'p:overlay2'
template = ' ::'

[[blocks.segments]]
type = 'path'
style = 'plain'
foreground = 'p:green'

[blocks.segments.properties]
style = 'full'

[[blocks.segments]]
type = 'text'
style = 'plain'
foreground = 'p:overlay2'
template = '{{ if .Segments.Contains "Git" }}on {{ else }}{{ end }}'

[[blocks.segments]]
type = 'git'
style = 'plain'
foreground = 'p:blue'
template = '{{ .HEAD }}'

[blocks.segments.properties]
branch_icon = ''

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
foreground_templates = [
  "{{if gt .Code 0}}p:red{{end}}",
  "{{if eq .Code 0}}p:mauve{{end}}",
]
template = "<b>❯</b>"
